### PR TITLE
Add ncp violation event

### PR DESCRIPTION
**Pull request by BlackCoyote**

### CODE REVIEW

**Comment by Morphan1** [comment]
Uh... Why even... How did you manage to code this with such an old method? Make it a ScriptEvent pls

**Comment by BlackCoyote** [comment]
this is copy paste from other events in depenizen written by you

**Comment by mcmonkey4eva** [comment]
@Morphan1 I said the same, he said most of Depenizen had this style.

**Comment by Morphan1** [comment]
https://github.com/DenizenScript/Depenizen/tree/master/bukkit/src/main/java/com/denizenscript/depenizen/bukkit/events

"most" being the 2 whole classes I can tell are not converted there?

**Comment by mcmonkey4eva** [comment]
gg

**Comment by BlackCoyote** [comment]
well i didn't say most

**Comment by Morphan1** [comment]
@BlackCoyote you could convert this one and those other 2 if you want to be beautiful

**Comment by BlackCoyote** [comment]
@Morphan1 OR you could accept this and convert the 3 of them in one go with your amazing skills :D

**Comment by Morphan1** [comment]
I'm not pulling ancient code. At least update it, it's not that hard to do. There's tons of examples in depenizen alone, and even more in d1

**Pull request closed without merging**
