### PR TITLE
Various tags, an event and NoteBlockAPI

### PR DESCRIPTION
**Pull request by Mwthorn**
4 less issues to-go. Tried to go for a less size of a pull request this time.

Tested with Minecraft version 1.12.2

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
I don't think a dependence on Jitpack is something that should be quietly slipped in.

**Comment by Mwthorn** [comment]
Should I download the jar files (to the lib folder) instead of linking to them?

**Comment by mcmonkey4eva** [comment]
in case of things that lack a maven server (Jitpack doesn't count): yes

**Comment by Mwthorn** [comment]
Gonna close this pull request since I've left it open for a while and have a few things left to do on it.
I'll re-open it again once I get time to finish it.

**Pull request closed without merging**
