### PR TITLE
pvparena add joins, leaves and exits events

### LINKED ISSUE #155: new event for pvpArena
Can you implement the event `on player enter pvparena` to catch player who enter on pvparena arena please ?

I only have `on pvparena starts` on the documentation.

Thank you

### PR DESCRIPTION
**Pull request by Oruss7**
PvpArena support:

- Add join event
- Add leave event

fix #155 

Thanks !

### CODE REVIEW

**Comment by Oruss7** [comment]
I add Exit event, i forgot it ^^

**Comment by mcmonkey4eva** [comment]
The meta has some poor English in it...
In particular ` an pvparena`.

**Comment by Oruss7** [comment]
You're right. Meta data are erronous and not well formed. It's fixed now.

**Comment by Oruss7** [comment]
Must be good now ?

**Pull request merged**
